apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r3y6c2zbh-python
  janus-idp.io/tekton: r3y6c2zbh-python
  backstage.io/kubernetes-id: r3y6c2zbh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r3y6c2zbh-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
